Implement job runner with priority queue
dctenna/software-design-and-algorithms pull request #13
Opened 2020-12-18 20:14 UTC by dctenna

2020-12-20 16:21 UTC, AlexHladin requested changes

2020-12-20 16:21 UTC, AlexHladin commented on 08_algorithms_and_data_structures_1/PriorityQueue.ts
> +  dequeue(): Job {
@dctenna, the `.pop` method returns element or undefined. I think the proper return type of the `dequeue` function is `Job | undefined`

2020-12-20 16:21 UTC, AlexHladin commented on 08_algorithms_and_data_structures_1/main.ts
> +jobRunner.runJobs();
code fails when I tried to run it :(

![image](https://user-images.githubusercontent.com/7945837/102718321-309b4b00-42f0-11eb-82e0-c9145d26c9af.png)

2020-12-20 21:03 UTC, dctenna commented on 08_algorithms_and_data_structures_1/PriorityQueue.ts
> +  dequeue(): Job {
@AlexHladin done

2020-12-20 21:04 UTC, dctenna commented on 08_algorithms_and_data_structures_1/main.ts
> +jobRunner.runJobs();
@AlexHladin fixed to run with ts-node as well.

2020-12-21 07:25 UTC, AlexHladin approved these changes

2020-12-21 10:51 UTC, merged