implement homework9
dctenna/software-design-and-algorithms pull request #14
Opened 2020-12-20 20:46 UTC by dctenna

2020-12-21 07:31 UTC, AlexHladin requested changes

2020-12-21 07:31 UTC, AlexHladin commented on 09_algorithms_and_data_structures_2/main.ts
> +const graph = new WeightedGraph(mockedAdjacencyMatrix);
@dctenna, the main goal is to create an application that can create the weighted graph and keep it as the adjacency matrix. You should create the adjacency matrix based on the graph.

2020-12-21 18:56 UTC, dctenna commented on 09_algorithms_and_data_structures_2/main.ts
> +const graph = new WeightedGraph(mockedAdjacencyMatrix);
@AlexHladin done

2020-12-21 20:15 UTC, AlexHladin commented on 09_algorithms_and_data_structures_2/main.ts
> +const graph = new WeightedGraph(mockedAdjacencyMatrix);
@dctenna, but where are you constructing adjacency matrix? I see that you have moched adjacency matrix?

2020-12-21 20:18 UTC, AlexHladin requested changes

2020-12-21 20:18 UTC, AlexHladin commented on 09_algorithms_and_data_structures_2/mocked-graph-data.ts
> +export const mockedAdjacencyMatrix = [
@dctenna, what for the mockedAdjacencyMatrix? You need to create the matrix itself. And it should look like on the screenshot
![image](https://user-images.githubusercontent.com/7945837/102818497-6caada80-43da-11eb-8f9c-36a8ea25e322.png)

2020-12-22 11:18 UTC, dctenna commented on 09_algorithms_and_data_structures_2/main.ts
> +const graph = new WeightedGraph(mockedAdjacencyMatrix);
@AlexHladin I am constructing it here: 
Mocked matrix is the same as constructed to show that we can construct any matrix.

![image](https://user-images.githubusercontent.com/14175498/102883079-111f3200-4458-11eb-8e9f-27cae60b1393.png)

2021-02-14 16:34 UTC, merged