04 design patterns part2
dctenna/software-design-and-algorithms pull request #7
Opened 2020-11-29 17:28 UTC by dctenna

2020-12-02 07:01 UTC, AlexHladin requested changes

2020-12-02 07:01 UTC, AlexHladin commented on 04_design_patterns/src/Shipment.ts
> +    const firstZipCodeChar = zipCode?.trim().charAt(0);
@dctenna, current logic should be implemented with the strategy pattern. Please, refer to examples here https://refactoring.guru/ru/design-patterns/strategy

2020-12-02 17:49 UTC, dctenna commented on 04_design_patterns/src/Shipment.ts
> +    const firstZipCodeChar = zipCode?.trim().charAt(0);
Done

2020-12-03 06:18 UTC, AlexHladin approved these changes

2020-12-03 09:15 UTC, merged