04-design-patterns-part4
dctenna/software-design-and-algorithms pull request #9
Opened 2020-11-29 20:32 UTC by dctenna

2020-12-07 07:07 UTC, AlexHladin requested changes

2020-12-10 21:58 UTC, dctenna commented on 04_design_patterns/src/Shipment.ts
> +    if (this._state.marks?.includes(MarkTypes.Fragile)) {
@AlexHladin done

2020-12-11 07:13 UTC, AlexHladin requested changes

2020-12-11 07:13 UTC, AlexHladin commented on 04_design_patterns/src/MarksDecorator.ts
> +export class MarksDecorator extends ShipmentDecorator {
@dctenna, what purpose of creating this class? Why don't you move this logic inside `ShipmentDecorator`?

2020-12-11 13:02 UTC, dctenna commented on 04_design_patterns/src/MarksDecorator.ts
> +export class MarksDecorator extends ShipmentDecorator {
Because it is more simple to move a concrete implementation to a separate class. 
It was described here:
https://refactoring.guru/uk/design-patterns/decorator/typescript/example

When all logic is described in ShipmentDecorator it will be difficult to implement more decorators with a different logic.

2020-12-11 16:41 UTC, dctenna commented on 04_design_patterns/src/MarksDecorator.ts
> +export class MarksDecorator extends ShipmentDecorator {
@AlexHladin fixed

2020-12-12 11:21 UTC, AlexHladin approved these changes

2020-12-13 18:50 UTC, merged